postgres:
  protocol: ""
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: postgres
  sslmode: disable
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
env: dev
port: 8080
cmc_cloud:
  endpoint: s3.cloud.cmctelecom.vn
  secret_access_key: S0TNxHmo3GWMgEBeF2QAUMGtfRCVE7aVNCh3DXaL
  access_key: 3S5MEJZLE2T2YCAG8ZWT
  bucket_name: content-management-dev