version: "3.9"

services:
  mafc_postgres:
    container_name: mafc_postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - go_develop
    restart: always
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
networks:
  elk:
  go_develop:
    driver: bridge
