version: "3.9"

services:
#  server:
#    container_name: maf_server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#    networks: ["go_develop"]
  postgres:
    container_name: maf_postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=content_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks: ["go_develop"]
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
networks:
  go_develop:
    driver: bridge