version: "3.9"

services:
  mafc_server:
    container_name: mafc_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mafc_postgres
    networks: ["go_develop"]
  mafc_postgres:
    container_name: mafc_postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks: ["go_develop"]
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
networks:
  elk:
  go_develop:
    driver: bridge
volumes:
  elasticsearch: