postgres:
  protocol: ""
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: cms_postgres
  sslmode: disable
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
env: dev
port: 8080
redis:
  host: redis
  port: "6379"
  username: ""
  password: ""
s3:
  aws_s3_region: ap-southeast-1
  aws_s3_bucket: test-cms-bucket-1
  aws_access_key: AKIA5MUA4AGOWXLSFJJA
  aws_secret_access_key: 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
  aws_session_token: ""